### ISSUE TITLE
GUI - Meal Plan Generator cannot return to menu when clicking the button

### ISSUE THREAD

**Issue by paulslss300** [CSC207-UofT/course-project-dj-wepny#100]
I was doing a scenario walkthrough of the GUI and I noticed clicking the Return to Menu button doesn't take me back to the menu interface. 

To reproduce the error:
1. Create a new user and be at the menu interface.
2. Click Generate Meal Plan
3. Choose 4 foods, press Enter.
4. Click Return to Menu.
5. Click Generate Meal Plan
6. Click Return to Menu.

Can someone see if they can reproduce the error and if so someone who's working on the GUI need to address this.

**Comment by paulslss300** [comment]
For me, going to Exercise Analyzer for the second time also has the bug where you cannot navigate back to the main menu interface.

**Comment by DavidM0808** [comment]
It's a relatively easy fix, the reason for that is that the return button on that interface does not have an active listener. I'll add that in.

**Comment by Enidx** [comment]
This issue has been fixed by Winnie in her local repo version as well! Can close this pr now.
