### ISSUE TITLE
GUI - view clipping

### ISSUE THREAD

**Issue by paulslss300** [CSC207-UofT/course-project-dj-wepny#101]
I noticed instances where UI clipping has prevented me to navigate the UI. Examples I found are 
1. Generating a food list with too many food items (e.g. > 6 items).
2. Going to the EER Analyzer for the second time. 

Please try to reproduce these clipping instances for validation. Also, expand the list if you find other instances.

**Comment by DavidM0808** [comment]
It's something to do with the GUI within the second constructor, so it's not that big of a deal. All I need to do is to set sizes of the Panel and the frame and the clipping issue should be resolved.

**Comment by paulslss300** [comment]
This reminds me, Exercise analyzer and Meal Plan Generator could potentially return a lot of text, so scrolling within the GUI may need to be implemented (or some other UI change).

**Comment by Enidx** [comment]
Yifan will be taking this on over the weekend to make a scroll bar! @yifanl27

**Comment by Enidx** [comment]
me and winnie finished implementing the scroll bar yesterday, this issue is now solved.
