### ISSUE TITLE
Personal Identification PIN not saved for GUI

### ISSUE THREAD

**Issue by paulslss300** [CSC207-UofT/course-project-dj-wepny#102]
After creating a new user the program informs you of your PIN, but after you re-run the GUI you cannot use your PIN to log in. Is this a bug or is this saving feature not implemented at the moment?

**Comment by DavidM0808** [comment]
The feature is not implemented yet as it involves the "update user profile" function of the program. We'll hopefully get it done today.

**Comment by Enidx** [comment]
This has been fixed by Winnie's latest pull request!
