### ISSUE TITLE
Better UX when creating a new user?

### ISSUE THREAD

**Issue by paulslss300** [CSC207-UofT/course-project-dj-wepny#103]
Currently if you provide an invalid input the program stops running and you need to re-run the program to proceed, which is not great for UX. We could considering prompting the user to re-enter their information instead.

**Comment by DavidM0808** [comment]
Where exactly is this happening? In what place does the program crash when we give it an invalid input? I need the specifics to fix the bug.

**Comment by paulslss300** [comment]
For example, this makes the app stop running 
![image](https://user-images.githubusercontent.com/50609667/144714493-5353033d-48bd-4cd0-95d7-0e582d7dd5eb.png)

**Comment by Enidx** [comment]
We did write code to catch the invalid input, but i dont know why there is a bug right not. Currently fixing.

**Comment by Enidx** [comment]
This can be closed now. Fixed in latest pr by Winnie
