### ISSUE TITLE
GUI - Cannot navigate from Disease Analyzer back to main menu.

### ISSUE THREAD

**Issue by paulslss300** [CSC207-UofT/course-project-dj-wepny#104]
After you press the submit button on Disease Analyzer interface there is no button for navigating back to the main menu. 
![image](https://user-images.githubusercontent.com/50609667/144696756-c89e41bb-6d3c-4535-b590-fa76425ad5cd.png)

**Comment by DavidM0808** [comment]
I noticed it too, I'll see what I can do to fix this. I think we just need to add another button and set it to invisible first, once the program finished running we can hide the "submit" button and shows the "return to menu" button instead.

**Comment by DavidM0808** [comment]
So I made it work, there's now a button that takes you back to the main menu after we have your potential disease. Next issue to solve is the difference between new users and existing users.

**Comment by Enidx** [comment]
Disease Analyzer is currently being modified by Jenny right now.  @paulslss300
