### ISSUE TITLE
GUI - Previous Analyzer results displayed when going back to the Analyzer interface for the second time

### ISSUE THREAD

**Issue by paulslss300** [CSC207-UofT/course-project-dj-wepny#105]
After using an Analyzer (e.g. Generate Meal Plan, Analyze Workout) and returning to the main menu, then going back to the Analyzer again you will see the results of the previous analysis instead of being able to use the Analyzer again.

**Comment by DavidM0808** [comment]
It's something in the Console GUI then. If our program's intended this way then we should be good. But if not, we'll take another look at ConsoleGUI

**Comment by paulslss300** [comment]
@Enidx Is this how the program should behave?

**Comment by Enidx** [comment]
Yep, that is how the program should behave.
New user -> creates profile -> choose a functionality -> go back to main menu -> access the reports directly.

Existing user -> chooses a report to access, if no information then they get to enter it now, if these is existing information in the file -> display report 

Existing user can edit their profile and change their information.

**Comment by paulslss300** [comment]
I see, though it feels strange a user can only ever have one report generated for them.

**Comment by Enidx** [comment]
they can log in as an existing user, and change the information

**Comment by paulslss300** [comment]
Do you mean when I re-log in I can generate a new Meal Plan/Exercises/Diseases report?

**Comment by Enidx** [comment]
if i re-log in, you can choose edit profile (winnie's new pr) and generate new report

**Comment by paulslss300** [comment]
Ok. Then this is not really an issue and I will be closing this thread.
