### ISSUE TITLE
GUI - User can type on prompt texts

### ISSUE THREAD

**Issue by paulslss300** [CSC207-UofT/course-project-dj-wepny#106]
The user can type in the prompt window of
1. Create new user interface 
![image](https://user-images.githubusercontent.com/50609667/144697039-d4b192e0-df5d-4f8a-9a92-dff9a82bda7c.png)

2. Create Meal Plan interface 
![image](https://user-images.githubusercontent.com/50609667/144697065-8e7890d8-5675-4e31-bc0e-dd5f42451574.png)

**Comment by DavidM0808** [comment]
To fix this, we just need to put in the code "textPane.setEditable(false)".

**Comment by Enidx** [comment]
Will be fixing this along with the bug previously mentioned about program crashing when input is invalid
