### ISSUE TITLE
Duplicate code - consoleforgui and system 

### ISSUE THREAD

**Issue by naomianne** [CSC207-UofT/course-project-dj-wepny#108]
I've noticed that 4 of the classes in system and consoleforgui are the same (HelperConsole, HelperUserInfo, ExistingUserConsole, and NewUserConsole). One of them is used for the GUIs and the other is used for the Console, which was for Phase 1. Is it better in terms of design to have two of them since they're used by different things? Or is there a way to have both the GUI and console use the same one, so we can reduce duplicate code? I'm not sure if this'll violate clean architecture.

**Comment by DavidM0808** [comment]
system is an older version of consoleforgui, so once we get everything done and working we'll delete it.

**Comment by Jennylin331431** [comment]
To add on, I think the consoleforGUI later on will mainly just be helpers for each GUI componenets, as most stuff will just come from presenter

**Comment by naomianne** [comment]
sounds good, i guess we can just delete the console part altogether as soon as the gui is complete then.
