### ISSUE TITLE
About Constants

### ISSUE THREAD

**Issue by DavidM0808** [CSC207-UofT/course-project-dj-wepny#83]
Here are some small concerns I have while refactoring the Constant class.

1. Right now all the smaller groups of constants extend Constant. However, the error messages in each of the subclasses are completely unrelated to the superclass. This means that having an inheritance relationship only increases coupling, which we don't want. Do you think it's okay to eliminate the "extends" statements for those classes?

2. For the ErrorConstants class I was thinking about renaming it to "Exceptions". Would it affect the program by that name change?

**Comment by Enidx** [comment]
1. Is there a purpose of having subclasses in general for constant? Since they just store different messages to be output, they can be just separate classes? avoid coupling as well
2. Changing it to  Exceptions sounds great, a more fitted name for this class

**Comment by DavidM0808** [comment]
1. I don't think it really has a purpose but the thing I did was an imitation to the Jshell case study. We should consult our TA about this just to be safe.
2. Alright I'll go change it after the meeting on the 29th.

**Comment by Enidx** [comment]
okok, remember to bring it up at today's meeting!
