### ISSUE TITLE
How do you connect Presenter with GUI

### ISSUE THREAD

**Issue by Enidx** [CSC207-UofT/course-project-dj-wepny#89]
Currently, me and Winnie is hard-coding the output the gui prints to the user. We know this shouldn't be right, and we need to somehow incorporate our presenter class with the GUI, but we are not sure how.

**Comment by Winnie1029** [comment]
So we kind of fix the problem and now the GUI can call the presenter and set text to what was initially printing out by the presenter so we no longer have to hard code the output. So to do that first check the custom create box and right click the text button and click restore default value. Then in the createUIComponent method create a new 
JLabel (or what ever you are customizing) for example,
 welcomeMessage = new JLabel(); then do welcomeMessage.setText(call the presenter).

**Comment by DavidM0808** [comment]
When you say "call the presenter" I got a bit confused. So for example, I want to get the output from an analyzer. Would the code be something like "welcomeMessage.setText(Presenter.retrieveOutput())"?
